name: Deploy Koyomi

on:
  push:
    paths:
      - "koyomi/**"

jobs:
  build:
    name: Deploy Koyomi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Create env
        working-directory: koyomi
        run: echo ${{ secrets.ENV_GRAPHQL }} > .env && echo ${{ secrets.ENV_SENTRY }} >> .env

      - name: Install dependencies
        working-directory: koyomi
        run: yarn

      - name: Build app
        working-directory: koyomi
        run: yarn build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=koyomi/build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - name: Delete env
        working-directory: koyomi
        run: rm .env
